// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvgzEZQdK2ghskRYbDoUMPrIgz8-xsYYA',
    appId: '1:1057167510210:web:2b8fdf01c83118f4e9095b',
    messagingSenderId: '1057167510210',
    projectId: 'helpnest-54527',
    authDomain: 'helpnest-54527.firebaseapp.com',
    storageBucket: 'helpnest-54527.firebasestorage.app',
    measurementId: 'G-QMVE8SGP8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNTxZZno0dAX6hOC1jcsi4yFajXCf317g',
    appId: '1:1057167510210:android:6283cbc7b24bebf4e9095b',
    messagingSenderId: '1057167510210',
    projectId: 'helpnest-54527',
    storageBucket: 'helpnest-54527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjK-ZOCcaUHZBbhGs24PaVTbDRmkpV0BU',
    appId: '1:1057167510210:ios:78d6717e27b5b507e9095b',
    messagingSenderId: '1057167510210',
    projectId: 'helpnest-54527',
    storageBucket: 'helpnest-54527.firebasestorage.app',
    iosBundleId: 'com.example.helpnest',
  );
}
